name: DeployApp

on:
  push:
    branches:
      - master

jobs:
  name: DeployApp
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Compile CSS and Javascript
      run: |
        npm install
        npm run prod
